server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://SERVICE-1
          predicates:
            - Path=/service1/**
        - id: service2
          uri: lb://SERVICE-2
          predicates:
            - Path=/service2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
