server:
  port: 0

spring:
  application:
    name: service-1
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
