spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
