server:
  port: 9001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
